### ISSUE TITLE
createSpyFromClass for chaining functions or provide example for that

### ISSUE THREAD

**Issue by csaszika** [hirezio/jasmine-auto-spies#17]
I'm using firestore for my angular app and my service looks like this:
```
@Injectable({
  providedIn: 'root',
})
export class Service {
  private readonly plansRef: AngularFirestoreCollection<any>;

  constructor(private readonly db: AngularFirestore) {
    this.ref = db.collection('/path');
  }

  addPlan(newObject: any): Promise<DocumentReference> {
    return this.ref.add(newObject);
  }

  deletePlan(id: Id): Promise<void> {
    return this.ref.doc(id).delete();
  }

  updatePlan(id: Id, updatedObject: any): Promise<void> {
    return this.ref.doc(id).update(updatedObject);
  }
}
```
So I should spy somehow chained functions like:
collection -> add
collection -> doc -> delete
collection -> doc -> update

I did not find nice solution for this case and it would be awesome if I can use a solution like this:
```
mockAngularFirestore = createSpyFromClass(AngularFirestore, ['collection', 'collection.add', 'collection.add.doc', ....]);
```

Now I can use only complex stubs.

If there is a nice solution that I did not find yet it is very welcome.
Thanks

**Comment by shairez** [comment]
Whenever you find yourself trying to fake an object that another fake is returning, this should be considered as a code smell.

There are 2 things you could do instead: 

1. Don't write a unit test for this code, but an integration test (without faking any of the dependencies)

2. Wrap firebase in a wrapper that behaves like you want it to behave and don't violate the [law of demeter](https://en.wikipedia.org/wiki/Law_of_Demeter).

**Comment by csaszika** [comment]
@shairez 
Yes, I totally agree. 

Now I use this solution:
```
const angularFirestoreStub = {
    collection: (path: string): any => {
      return {
        add: (data: object): void => {},
        doc: (id: string): object => {
          return {
            delete: (): void => {},
            update: (): void => {},
          };
        },
      };
    },
  };

  Given(() => {
    spyCollection = spyOn(angularFirestoreStub, 'collection').and.returnValue({
      add: (data: object): void => {},
      doc: (id: string): object => {
        return {
          delete: (): void => {},
          update: (): void => {},
        };
      },
    });
  });
```
This works well and yeah I can extract the return value object too, but at least it is easy and reusable.
Thanks for the response :)
