### ISSUE TITLE
Can't compile and run code that uses "resolveWith" function.

### ISSUE THREAD

**Issue by elira** [hirezio/jasmine-auto-spies#22]
**Describe the bug**
VSCode does not recognize the resolveWith function mentioned in the docs:

**To Reproduce**
1. Try using the code in the Readme file:
```
let storeSpy: Spy<Store>;
storeSpy = createSpyFromClass(Store);
storeSpy.selectSnapshot.and.resolveWith({});
```
**Expected behavior**
Code should compile and work

**Screenshots**
![image](https://user-images.githubusercontent.com/405275/85257629-d28bc900-b46e-11ea-872c-0f9da112faa3.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: desktop
 - OS: Windows 10 
 - Browser N/A
 - Version N/A

**Additional context**
Using angular 9

**Comment by shairez** [comment]
Thanks for the report @elira !

2 questions - 

1. Which version of jasmine-auto-spies are you using?

2. does `selectSnapshot` returns a promise or an Observable?

**Comment by elira** [comment]
Thanks for your reply @shairez !

1. "jasmine-auto-spies": "^5.4.0",
2. selectSnapshot returns an object. Ayayay. Sorry. I'll close this. :)

**Comment by shairez** [comment]
Sure thing @elira and no problem!
