### ISSUE TITLE
Support older versions of angular/typescript:

### ISSUE THREAD

**Issue by Bnaya** [hirezio/jasmine-auto-spies#7]
This feature might lead the way to have graceful degradation support for typescript < 2.8
https://github.com/Microsoft/TypeScript/pull/26568

**Comment by shairez** [comment]
Thanks @Bnaya !

Looks amazing!

**Comment by shairez** [comment]
@Bnaya we talked about it offline, I don't remember if the conclusion was that this might not work well eventually

What do you say? should we close this issue?

**Comment by Bnaya** [comment]
Lets
