### ISSUE TITLE
Support for Angular 7

### ISSUE THREAD

**Issue by idanaim** [hirezio/jasmine-auto-spies#9]
Trying to update angular version with ng update  and get this: 
![jasmine-problem](https://user-images.githubusercontent.com/10272956/48554437-1445ac80-e8e7-11e8-9695-b98201d559c9.png)

**Comment by treestructure** [comment]
Same here when updating to Angular 8. I just ran npm i -f typescript@3.4.x before running ng update. Jasmine Auto spies seemed to work well with Typescript 3.4
